export default { 
    DATA_BASE_CONNECTION_ERROR : 1000,
    ERROR_LOADING_DATA_FROM_DATABASE : 1002,
    ERROR_LOADING_DATA_FROM_EXTERNAL_SOURCE : 1003,
    ENABLE_TO_SAVE_RECORD_TO_DATA_BASE : 1004,
    ENABLE_TO_UPDATE_RECORD_IN_DATA_BASE: 1005,
    DATA_NOT_FOUND: 1006,
    PROCESS_TERMINATED: 2000,

  
    IP_NOT_VALID: {
        message: "Invalid IPv4 address.",
        code: "5004"
    }
}